export { default as Logo } from './gnb_logo.svg';
export { default as Programmer } from './Group 289.svg';
export { default as Designer } from './Group 290.svg';
export { default as GreenQuote1 } from './greenQuote1.svg';
export { default as GreenQuote2 } from './greenQuote2.svg';
export { default as BlueQuote1 } from './blueQuote1.svg';
export { default as BlueQuote2 } from './blueQuote2.svg';
export { default as DPM } from './dpm.svg';
export { default as Meet } from './Group 1522.svg';
export { default as Gmail } from './ic_gmail.svg';
export { default as Kakao } from './ic_kakao.svg';
export { default as Instagram } from './ic_instagram.svg';
export { default as Memoji } from './Memoji.svg';
export { default as T } from './T.svg';
export { default as RightArrow } from './RightArrow.svg';
export { default as LeftArrow } from './LeftArrow.svg';
export { default as LongArrow } from './arrow-long.svg';
export { default as ShortArrow } from './arrow-short.svg';
export { default as ShortArrowGreen } from './arrow-short-green.svg';
