export { default as Logo } from './gnb_logo.svg';
export { default as Programmer } from './Group 289.svg';
export { default as Designer } from './Group 290.svg';
export { default as GreenQuote1 } from './greenQuote1.svg';
export { default as GreenQuote2 } from './greenQuote2.svg';
export { default as BlueQuote1 } from './blueQuote1.svg';
export { default as BlueQuote2 } from './blueQuote2.svg';
export { default as FooterLogo } from './logo_footer.svg';
export { default as FacebookLogo } from './ic_sns_facebook.svg';
export { default as InstagramLogo } from './ic_sns_instagram.svg';
export { default as MediumLogo } from './ic_sns_medium.svg';
export { default as ProjectBackgroundImage } from './project_background_image.svg';
export { default as ArrowDownGreen } from './arrow_down_green.svg';
export { default as Meet } from './Group 1522.svg';
export { default as Gmail } from './ic_gmail.svg';
export { default as Kakao } from './ic_kakao.svg';
export { default as Memoji } from './Memoji.svg';
export { default as T } from './T.svg';
