export { BehanceIcon } from './BehanceIcon';
export { FacebookIcon } from './FacebookIcon';
export { GithubIcon } from './GithubIcon';
export { InstagramIcon } from './InstagramIcon';
export { LinkedinIcon } from './LinkedinIcon';
export { MailIcon } from './MailIcon';
export { MediumIcon } from './MediumIcon';
export { ScrollBottomIcon } from './ScrollBottomIcon';
export { WebIcon } from './WebIcon';
